services:
  blogo:
    image: pluja/blogo:latest
    container_name: blogo
    restart: unless-stopped
    volumes:
      - ./articles:/app/articles
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # CONFIG
      BLOGO_TITLE: My Blog
      BLOGO_DESCRIPTION: My Custom Blog!
      BLOGO_KEYWORDS: easy
      BLOGO_URL: http://localhost:3000
      BLOGO_ANALYTICS: '<script defer src="https://www.googletagmanager.com/gtag/js?id=G-T7RRSPMFVH"></script>'
      TIMEZONE: UTC

      # NOSTR CONFIG
      PUBLISH_TO_NOSTR: false
      #NOSTR_NSEC: ""
      #NOSTR_RELAYS: "wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"
